"""Tests for `strip_svg_graph_metadata.py`.

The script exists to stop a fixture from stating its own answer, so what these assert is that
the answer really is gone, that the drawing still renders the same, and that an element's type
survives -- knowing a stroke is a connector is not knowing what it connects.
"""

from __future__ import annotations

import unittest

from strip_svg_graph_metadata import strip

GRAPHVIZ_NODE = (
    '<g id="node1" class="node">\n<title>a</title>\n<polygon fill="#a6cee3" stroke="black" points="0,0 1,1"/>\n</g>\n'
)
GRAPHVIZ_EDGE = (
    '<g id="edge1" class="edge">\n'
    "<title>a&#45;&gt;b</title>\n"
    '<path fill="none" stroke="black" d="M63,-234.8C63,-227.16 63,-208.24"/>\n'
    "</g>\n"
)
GRAPHVIZ_CLUSTER = (
    '<g id="clust1" class="cluster">\n'
    "<title>cluster_ingest</title>\n"
    '<polygon fill="#eef6fb" stroke="black" points="8,-148 8,-297 84,-297"/>\n'
    "</g>\n"
)
GRAPHVIZ_ROOT = '<g id="graph0" class="graph" transform="scale(1 1)">\n<title>whole_graph</title>\n'

MERMAID_EDGE = (
    '<path d="M1,2L3,4" id="L_start_auth_0" data-id="L_start_auth_0"'
    ' class="flowchart-link" marker-end="url(#my-svg_flowchart-v2-pointEnd)"/>'
)
PLANTUML_EDGE = (
    '<g id="Read config-to-Open input" class="link" data-source-line="4">'
    '<path d="M1,2L3,4" fill="none" style="stroke:#181818;"/></g>'
)


class TitleStrippingTest(unittest.TestCase):
    def test_should_remove_the_node_id_from_a_node_group(self) -> None:
        self.assertNotIn("<title>", strip(GRAPHVIZ_NODE))

    def test_should_remove_the_edge_endpoints_from_an_edge_group(self) -> None:
        stripped = strip(GRAPHVIZ_EDGE)
        self.assertNotIn("a&#45;&gt;b", stripped)
        self.assertNotIn("<title>", stripped)

    def test_should_remove_the_cluster_name_so_a_container_is_not_labelled_as_one(self) -> None:
        self.assertNotIn("cluster_ingest", strip(GRAPHVIZ_CLUSTER))

    def test_should_keep_the_root_title_that_names_the_whole_drawing(self) -> None:
        self.assertIn("<title>whole_graph</title>", strip(GRAPHVIZ_ROOT + GRAPHVIZ_NODE))


class IdentifierStrippingTest(unittest.TestCase):
    def test_should_remove_a_mermaid_edge_id_naming_both_endpoints(self) -> None:
        stripped = strip(MERMAID_EDGE)
        self.assertNotIn("L_start_auth_0", stripped)
        self.assertNotIn("data-id", stripped)

    def test_should_remove_a_plantuml_edge_id_naming_both_endpoints(self) -> None:
        self.assertNotIn("Read config-to-Open input", strip(PLANTUML_EDGE))

    def test_should_keep_an_id_the_document_points_at_with_url(self) -> None:
        marker = '<marker id="arrow"/><path marker-end="url(#arrow)" d="M1,2L3,4"/>'
        self.assertEqual(marker, strip(marker))

    def test_should_keep_an_id_the_document_points_at_with_href(self) -> None:
        used = '<path id="outline" d="M1,2"/><use xlink:href="#outline"/>'
        self.assertEqual(used, strip(used))

    def test_should_keep_an_id_a_stylesheet_selector_points_at(self) -> None:
        styled = '<style>#my-svg .node rect{fill:#fff}</style><svg id="my-svg"><g class="node"/></svg>'
        self.assertIn('id="my-svg"', strip(styled))

    def test_should_keep_an_opaque_id_that_names_nothing_but_is_referenced(self) -> None:
        # LibreOffice numbers its shapes id1..idN and refers to them from clip paths.
        libreoffice = '<clipPath id="id3"><rect/></clipPath><g clip-path="url(#id3)"/>'
        self.assertEqual(libreoffice, strip(libreoffice))


class CommentStrippingTest(unittest.TestCase):
    def test_should_remove_a_graphviz_comment_restating_an_edge(self) -> None:
        self.assertNotIn("a&#45;&gt;b", strip("<!-- a&#45;&gt;b -->\n" + GRAPHVIZ_EDGE))

    def test_should_remove_a_plantuml_comment_restating_an_edge(self) -> None:
        commented = "<!--link Read config to Open input-->" + PLANTUML_EDGE
        self.assertNotIn("Read config", strip(commented))

    def test_should_remove_the_producer_banner_because_provenance_lives_in_the_manifest(self) -> None:
        banner = "<!-- Generated by graphviz version 15.1.1 -->\n<svg/>"
        self.assertEqual("<svg/>", strip(banner))


class PreservationTest(unittest.TestCase):
    def test_should_preserve_every_byte_of_geometry(self) -> None:
        stripped = strip(GRAPHVIZ_NODE + GRAPHVIZ_EDGE + GRAPHVIZ_CLUSTER)
        self.assertIn('points="0,0 1,1"', stripped)
        self.assertIn('d="M63,-234.8C63,-227.16 63,-208.24"', stripped)
        self.assertIn('points="8,-148 8,-297 84,-297"', stripped)

    def test_should_keep_the_class_that_gives_an_element_its_type(self) -> None:
        for original in (GRAPHVIZ_NODE, GRAPHVIZ_EDGE, MERMAID_EDGE, PLANTUML_EDGE):
            stripped = strip(original)
            self.assertIn("class=", stripped)

    def test_should_keep_the_text_a_node_is_labelled_with(self) -> None:
        labelled = '<g id="node1" class="node"><title>a</title><text>Start</text></g>'
        self.assertIn("<text>Start</text>", strip(labelled))

    def test_should_leave_a_hand_authored_svg_without_graph_metadata_untouched(self) -> None:
        hand_authored = '<svg><rect x="0" y="0"/><text>Start</text></svg>'
        self.assertEqual(hand_authored, strip(hand_authored))


if __name__ == "__main__":
    unittest.main()
